# Generated by Django 6.0.3 on 2026-03-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='permitir_vender_sin_stock',
            field=models.BooleanField(default=False, help_text='Si está activo, el producto puede venderse aunque el stock no alcance.', verbose_name='Permitir vender sin stock'),
        ),
    ]
