# Generated by Django 6.0.3 on 2026-03-12 06:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_add_fecha_nacimiento'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vcto.')),
                ('tipo_comprobante', models.CharField(choices=[('boleta', 'Boleta de Venta Electrónica'), ('factura', 'Factura Electrónica'), ('proforma', 'Proforma')], default='boleta', max_length=20)),
                ('serie', models.CharField(default='BB01', max_length=10)),
                ('numero_comprobante', models.CharField(blank=True, max_length=20)),
                ('tipo_operacion', models.CharField(choices=[('venta_interna', 'VENTA INTERNA'), ('venta_externa', 'VENTA EXTERNA')], default='venta_interna', max_length=20)),
                ('descuento_global', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Dscto. global (%)')),
                ('es_proforma', models.BooleanField(default=False, verbose_name='PROFORMA')),
                ('observaciones', models.TextField(blank=True)),
                ('condicion_pago', models.CharField(blank=True, max_length=100, verbose_name='Cond. pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitido', 'Emitido'), ('anulado', 'Anulado')], default='emitido', max_length=20)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='clientes.cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
            },
        ),
    ]
