# Generated by Django 6.0.3 on 2026-03-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_periodo', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('anual', 'Anual')], max_length=20)),
                ('duracion_dias', models.PositiveIntegerField(help_text='Duración en días (7=semanal, 15=quincenal, 30=mensual, 365=anual)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_promocion', models.BooleanField(default=False, verbose_name='Es promoción')),
                ('descripcion_promocion', models.TextField(blank=True, verbose_name='Detalle de promoción')),
                ('fecha_inicio_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha inicio vigencia (opcional)')),
                ('fecha_vencimiento_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha vencimiento vigencia (opcional)')),
                ('renovacion', models.CharField(choices=[('automatica', 'Automática'), ('manual', 'Manual')], default='manual', max_length=20, verbose_name='Renovación')),
                ('dias_gracia_mora', models.PositiveIntegerField(default=0, help_text='Días después del vencimiento antes de considerar en mora', verbose_name='Días de gracia (mora)')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['nombre'],
            },
        ),
    ]
