# Generated by Django 4.2.29 on 2026-03-12 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_sueldohistorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField(verbose_name='Hora de ingreso')),
                ('fecha_hora_termino', models.DateTimeField(blank=True, null=True, verbose_name='Hora de término')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='trabajadores.trabajador')),
            ],
            options={
                'verbose_name': 'Asistencia de trabajador',
                'verbose_name_plural': 'Asistencias de trabajadores',
                'ordering': ['-fecha_hora_ingreso'],
            },
        ),
    ]
