# Generated by Django 4.2.29 on 2026-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_add_asistencia_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagotrabajador',
            name='periodo_referencia',
            field=models.CharField(choices=[('quincena_1', 'Quincena 1'), ('quincena_2', 'Quincena 2'), ('mes', 'Mes completo')], default='mes', max_length=20, verbose_name='Periodo referido'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='periodo_pago',
            field=models.CharField(choices=[('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='mensual', max_length=20, verbose_name='Periodo de pago'),
        ),
    ]
