# Generated by Django 4.2.29 on 2026-03-12 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajadores', '0004_add_periodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('tardanzas', 'Tardanzas'), ('afp', 'AFP'), ('onp', 'ONP'), ('incumplimientos', 'Incumplimientos')], max_length=20)),
                ('periodo_referencia', models.CharField(choices=[('quincena_1', 'Quincena 1'), ('quincena_2', 'Quincena 2'), ('ambas', 'Ambas quincenas')], default='quincena_1', max_length=20, verbose_name='Periodo referido')),
                ('mes_ref', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes de referencia')),
                ('anio_ref', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de referencia')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='trabajadores.trabajador')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descuentos_trabajadores_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descuento a trabajador',
                'verbose_name_plural': 'Descuentos a trabajadores',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdelantoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del adelanto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descontar_de', models.CharField(choices=[('ambas_quincenas', 'Ambas quincenas'), ('quincena_1', 'Solo quincena 1'), ('quincena_2', 'Solo quincena 2')], default='ambas_quincenas', max_length=20, verbose_name='Descontar de')),
                ('mes_ref', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes de referencia')),
                ('anio_ref', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año de referencia')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='trabajadores.trabajador')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adelantos_trabajadores_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adelanto a trabajador',
                'verbose_name_plural': 'Adelantos a trabajadores',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
