# Generated by Django 4.2.29 on 2026-03-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_add_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField(verbose_name='Hora de ingreso')),
                ('fecha_hora_egreso', models.DateTimeField(blank=True, null=True, verbose_name='Hora de egreso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha_hora_ingreso'],
            },
        ),
    ]
