# Generated by Django 4.2.29 on 2026-03-12 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_add_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaInvitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre del invitado')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='DNI (opcional)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to='clientes.asistencia')),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
